$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function Require-Text([string]$path, [string]$needle) {
    $text = Get-Content -Raw (Join-Path $root $path)
    if (-not $text.Contains($needle)) { throw "Missing '$needle' in $path" }
}

function Reject-Text([string]$path, [string]$needle) {
    $text = Get-Content -Raw (Join-Path $root $path)
    if ($text.Contains($needle)) { throw "Forbidden '$needle' in $path" }
}

Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'Intent.ACTION_OPEN_DOCUMENT_TREE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'takePersistableUriPermission'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'DocumentsContract.EXTRA_INITIAL_URI'

Require-Text 'app\src\main\AndroidManifest.xml' 'MANAGE_EXTERNAL_STORAGE'
Reject-Text 'app\src\main\AndroidManifest.xml' 'READ_EXTERNAL_STORAGE'
Reject-Text 'app\src\main\AndroidManifest.xml' 'WRITE_EXTERNAL_STORAGE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'migrateRuntimeStateAfterUpdate'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'KEY_INSTALLED_VERSION_CODE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'new File(getFilesDir(), "mkxp_runtime")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\DirectStorageResolver.java' 'Environment.isExternalStorageManager()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\DirectStorageResolver.java' 'com.android.externalstorage.documents'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\DirectStorageResolver.java' 'new File("/storage", volume)'

$scanner = 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java'
foreach ($needle in @('rgss301','rgss202','rgss102','scripts.rvdata2','scripts.rvdata','scripts.rxdata','rpg_rt.ldb','rpg_rt.lmt','rmmz_core.js','rpg_core.js','.easyrpg','.zip')) {
    Require-Text $scanner $needle
}

Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'GameMaterializer.mirror'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'DirectStorageResolver.resolveGameDirectory'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'RgssCompatInstaller.prepareRuntime'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'EXTRA_COMPAT_ROOT_PATH'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatRootPath, "compat/common")'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'preloads.put("compat/common/ruby_classic_wrap.rb")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RgssCompatInstaller.java' 'mkxp_compat/'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RgssCompatInstaller.java' 'cleanupGeneratedGameCompat'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\config.cpp' 'gameFolder + "/UserData/AppData"'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\config.cpp' 'customDataPath += ''/'''
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' '게임 실행 준비중'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'if (!direct) PersistentSaveManager.prepareRgss'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\patches.rb' 'To the Moon Android path separator fix'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'freebird_language_scene?'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'RPGMP_FREEBIRD_NIL_VISIBLE'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'FREEBIRD NIL VISIBLE PREPASS'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'FREEBIRD NIL visible= guard active'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\mouse_skip.rb' 'def pos_x'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\mouse_skip.rb' 'def pos_y'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\mouse_skip.rb' 'def position'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'GameMaterializer.materializeEasyRpg'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'EasyRpgArchiveResolver.projectPath(project)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'overridePendingTransition(0, 0)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'LibretroEasyRpgActivity.class'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'prepareEasyRpgLibretro'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'EasyRpgPlayerActivity'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'String project = GameScanner.documentUri(treeUri, game.documentId).toString()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameMaterializer.java' 'easyrpg_project_mirror'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameMaterializer.java' 'if (!game.archive) return mirror(context, treeUri, game, progress)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameMaterializer.java' 'game.documentId.equals(child.documentId)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgArchiveResolver.java' 'rpg_rt.ldb'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgArchiveResolver.java' 'rpg_rt.lmt'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgArchiveResolver.java' 'easy_rt.edb'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgArchiveResolver.java' 'easy_rt.emt'
Require-Text 'easyrpg_runtime\src\main\AndroidManifest.xml' 'SDL_ENV.SDL_APP_NAME" android:value="RPG Maker Player"'
Reject-Text 'easyrpg_runtime\src\main\AndroidManifest.xml' 'SDL_ENV.SDL_APP_NAME" android:value="EasyRPG Player"'
Require-Text 'app\src\main\AndroidManifest.xml' 'android:theme="@style/RpgmpEasyRpgPlayerTheme"'
Require-Text 'app\src\main\res\values\styles.xml' 'android:windowDisablePreview">true'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'overridePendingTransition(0, 0)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibretroEasyRpgActivity.java' 'System.loadLibrary("rpgmp_libretro_host")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibretroEasyRpgActivity.java' 'VirtualGamepadView'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibretroEasyRpgActivity.java' 'libeasyrpg_libretro.so'
Require-Text 'app\src\main\cpp\libretro_host.cpp' 'retro_load_game'
Reject-Text 'app\src\main\cpp\libretro_host.cpp' 'AAudioStream_write'
Require-Text 'app\src\main\cpp\libretro_host.cpp' 'AAudioStreamBuilder_setDataCallback'
Require-Text 'app\src\main\cpp\libretro_host.cpp' 'g_audio_ring'
Require-Text 'app\src\main\cpp\libretro_host.cpp' 'AAUDIO_ERROR_DISCONNECTED'
Require-Text 'app\src\main\cpp\libretro_host.cpp' 'ANativeWindow_lock'
Require-Text 'app\src\main\cpp\libretro_host.cpp' 'RETRO_ENVIRONMENT_SHUTDOWN'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'TimGM6mb.sf2'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'easyrpg-player'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'Soundfont'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'Font1'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'Font2'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' '"rtp", "easyrpg-player", "Soundfont"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' '"rtp", "easyrpg-player", "Font"'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'treeUri, "easyrpg", "Soundfont"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, rootId, "_image")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, rtpId, "xp")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, rtpId, "vx")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, rtpId, "vxace")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, rtpId, "fonts")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, rtpId, "easyrpg-player")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, easyRpgId, "Soundfont")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LibraryFolderLayout.java' 'ensureDirectory(context, treeUri, easyRpgId, "Font")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'LibraryFolderLayout.ensure(this, root)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'void onEngineSettings()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'settingRow(c, layout, 2'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'listener.onEngineSettings()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'showEngineSettingsDialog'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'showEngineKeyMapDialog'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EngineSettings.java' 'static String rubyMode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EngineSettings.java' 'static String renderMode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EngineSettings.java' 'static void saveEasyChoices'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EngineSettings.java' 'static void saveKeyMap'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'EngineSettings.rubyMode(activity, game.engine)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'EngineSettings.renderMode(activity, game.engine)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameKeyMap.java' 'EngineSettings.keyMap(activity, game.engine)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'static final String INHERIT = "inherit"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EasyRpgCoreSettings.java' 'gameSoundfontChoices'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'EasyRpgCoreSettings.prepareSystemDirectory'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'MIDI SoundFont'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameEntry.java' 'withTitle'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'return game.withTitle(custom.trim())'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'EASYRPG_CORE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'EXTRA_RUBY_MODE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'saveGameSettings'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'scanRubyRuntime'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'RubyRuntimeDetector.resolveAutomatic'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'LibretroEasyRpgActivity.EXTRA_KEYMAP'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameKeyMap.java' 'KEYCODE_BUTTON_START'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameKeyMap.java' 'KEYCODE_BUTTON_SELECT'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyRuntimeDetector.java' 'deep[ruby18='
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyRuntimeDetector.java' 'libprobe-ruby31.so'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyRuntimeDetector.java' 'DETECTOR_REV = 3'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyRuntimeDetector.java' 'game.engine == GameEntry.Engine.VXACE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyRuntimeDetector.java' 'RubyScriptsArchive.extract'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyScriptsArchive.java' 'InflaterInputStream'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyScriptsArchive.java' 'Unsupported Ruby Marshal version'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatCommon, "win32_wrap.rb")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'RPGMP_CICPOFFS_COMPAT'
Require-Text 'tools\patch_mkxpz_cicpoffs_pre_eval.py' 'getenv("RPGMP_CICPOFFS_COMPAT")'
Require-Text 'tools\patch_mkxpz_cicpoffs_pre_eval.py' 'RAPI_FULL <= 193'
Require-Text 'tools\patch_mkxpz_cicpoffs_pre_eval.py' 'RPGMP_ANDROID_CICPOFFS_SKIP_RUBY31'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameLog.java' 'new File(root, "_log")'
Require-Text 'tools\build_selfbuilt_mkxp_arm64.sh' 'patch_mkxpz_cicpoffs_pre_eval.py'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatCommon, "mkxp_wrap.rb")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatCommon, "ruby_classic_wrap.rb")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatCommon, "ruby31_legacy_wrap.rb")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'root.put("rubyLoadpath", rubyLoadpath)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RgssCompatInstaller.java' 'ASSET_ROOT + "/ruby31lib"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatCommon, "native_ext_compat.rb")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatCommon, "fix_volume.rb")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'root.put("fullscreen", true)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'root.put("integerScalingActive", true)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'root.put("integerScalingLastMile", true)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'mkxp-z-31'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'GameKeyMap.remap'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'nativeSendQuit'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'applyGameUserEnvironment'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'Os.setenv("APPDATA"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'Os.setenv("LOCALAPPDATA"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'Os.setenv("HOME"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'Os.setenv("TEMP"'
Require-Text 'app\src\main\assets\rgss_compat\common\win32_wrap.rb' 'class WritePrivateProfileString'
Require-Text 'app\src\main\assets\rgss_compat\common\win32_wrap.rb' 'File.open(filename, ''wb'')'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RgssCompatInstaller.java' 'rgss_compat'

Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'rpgmaker.local'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'VirtualGamepadView'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'Input._currentState'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'GameKeyMap.remap'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'web.destroy()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'font-family:GameFont'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'bundledFont'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'encryptedOggAudio'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'oggAudioAvailable'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' "AudioManager.audioFileExt=function(){return '.ogg';}"
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmpResumeAudio'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'Uri.decode(uri.getEncodedPath())'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'EXTRA_RENDER_MODE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' '?webgl'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' '?canvas'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'URLDecoder.decode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'finalMvRenderSpinner'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'finalMvScanButton'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'runMvMzCompatibilityScan'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'KEYCODE_BUTTON_L1'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'KEYCODE_BUTTON_R1'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'scrollLibraryPage'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'VelocityTracker'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'OverScroller'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'scroller.fling'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'scrollLibraryPage(int direction)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' '"_image".equalsIgnoreCase(child.name)'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\config.cpp' 'SDLRWStream iniFile(iniFileName.c_str(), "r")'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\config.cpp' 'if (ic.load(iniFile.stream()))'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\config.cpp' 'game.title = Encoding::convertString(game.title)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' 'Map<String, String> thumbnailCatalog = buildThumbnailCatalog(context, treeUri, rootChildren)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameEntry.java' 'thumbnailDocumentId'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'loadGameThumbnails'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'setGameThumbnail'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'handleControllerKey(int keyCode)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'KEYCODE_BUTTON_SELECT'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'KEYCODE_BUTTON_L2'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'KEYCODE_BUTTON_R2'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'dispatchGenericMotionEvent'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'prepareDialogForGamepad'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'KEYCODE_DPAD_CENTER'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'KEY_RECENT_GAMES'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'recordRecentGame(game)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'PLATFORM_LABELS'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'PLATFORM_ENGINES'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'launcher_bg_v048.png'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'drawPlatformTabs'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'handlePlatformTouch'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'cyclePlatform'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'drawButtonHints'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'Color.argb(118, 82, 88, 96)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'c.drawBitmap(brandLogoBitmap'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'brandLogoBitmap = BitmapFactory.decodeStream(input)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'float proportionalMax = cardW * 1.55f;'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'float absoluteMax = s(190);'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'rewrite_top_level_module_include!'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'COMMON TOPLEVEL INCLUDE PREPASS'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'Object.send(:include, #{mod})'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'RgssRtpFallback.searchRootsFromRtpRoot(sharedRtpRoot, engine)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RgssRtpFallback.java' 'searchRootsFromRtpRoot(File rtpRoot, String engine)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RgssRtpFallback.java' 'findDirectoryIgnoreCase(rtpRoot, "fonts")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RgssRtpFallback.java' 'return "vxace"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' 'buildThumbnailCatalog(context, treeUri, rootChildren)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' 'thumbnailCatalog.get((node.name + ".png").toLowerCase(Locale.ROOT))'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' '!"_image".equalsIgnoreCase(child.name)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' 'findRootDirectoryDocumentId(rootChildren, "rtp")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' '!"rtp".equalsIgnoreCase(child.name)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'GameMaterializer.mirrorSharedRtp'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'EXTRA_RTP_ROOT_PATH'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'ui/brand_logo.png'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'aspect >= 2.0f ? 0.94f : 0.86f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'styleReleaseDialogWindow(dialog, 0.70f, 0.82f)'
Require-Text 'app\src\main\AndroidManifest.xml' 'android:icon="@mipmap/ic_launcher"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'prepareRgss'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'prepareEasyRpg'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'String remote = game.saveRootDocumentId;'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'EASYRPG_GAME_ROOT'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'copyEasyRpgSavesSafToLocal'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'clearStaleRgssSaveFiles'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'isLauncherManagedLegacyPath'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'ensureCentralEngineSaveDir(context, treeUri, game.saveRootDocumentId, "rgss")'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\PersistentSaveManager.java' 'ensureCentralEngineSaveDir(context, treeUri, game.saveRootDocumentId, "easyrpg")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'EXTRA_SAVE_ROOT_ID'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' '__RPGMP_SAVE__'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'original game-folder save bridge active'
if (-not (Test-Path 'app\src\main\assets\ui\brand_logo.png')) { throw 'SteamOS brand logo asset missing' }
if (-not (Test-Path 'app\src\main\res\mipmap-xxxhdpi\ic_launcher.png')) { throw 'release launcher icon missing' }
$launcherViewSource = Get-Content 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' -Raw
if ($launcherViewSource.Contains('WOLF ?쒖쇅')) { throw 'release UI still contains WOLF exclusion development note' }
if (-not (Test-Path 'app\src\main\assets\ui\launcher_bg_v048.png')) { throw 'SteamOS launcher background asset missing' }
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'onWindowFocusChanged'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'WindowInsetsController'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'setNavigationBarContrastEnforced(false)'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'enterRpgmpImmersive'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'onWindowFocusChanged'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'WindowInsetsController'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'scanMvMzCompatibility'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'saveMvRenderMode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'rgssMouseMode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'writeMouseMode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'finalRgssMouseSpinner'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'saveRgssMouseMode'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'Mouse PREPASS AUTO PASS'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'mouse_mode.txt'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'RPGMP_LEGACY_INTEGER_TO_A'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'def to_a'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'DLDB CHEAT PREPASS'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'rpgvxacecheatsystem'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'legacy_mouse_extension?'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'name.strip =~ /\Amouse\s*[23]\z/i'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'Mouse PREPASS AUTO BRIDGE legacy extension'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'dldb_cheat_script?'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'DLDB CHEAT PREPASS'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'Script patch skipped'
Require-Text 'app\src\main\assets\rgss_compat\common\ruby_classic_wrap.rb' 'def write(filename, string, offset = nil, *open_args)'
Require-Text 'app\src\main\assets\rgss_compat\common\ruby_classic_wrap.rb' 'def binwrite(filename, string, offset = nil)'
Require-Text 'app\src\main\assets\rgss_compat\common\ruby_classic_wrap.rb' 'def binread(filename, length = nil, offset = 0)'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\mouse_skip.rb' 'RPGMP_DisabledMouse'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\mouse_skip.rb' 'def clear_path'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\mouse_skip.rb' 'def find_path(*args)'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\mouse_skip.rb' 'def update_pathfinding(*args)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'rpgmp-android-late'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmpAudioQueue'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'onGameSettings'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'ViewConfiguration.getLongPressTimeout()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'scrollOffsetPx'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'drawBusyOverlay'
foreach ($needle in @('KEYCODE_BUTTON_START','KEYCODE_BUTTON_SELECT','KEYCODE_BUTTON_L1','KEYCODE_BUTTON_L2','KEYCODE_BUTTON_R1','KEYCODE_BUTTON_R2')) {
    Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' $needle
}
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'drawAnalog'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'updateAnalog'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'Only claim gestures that actually start on a virtual control'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'interface MouseListener'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'setMouseMode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'onWheel(-120f)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'onButton(2, true)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'EXTRA_MOUSE_MODE'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'sendMouseMove'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'new WheelEvent'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'warpMousePosition'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'setOnTouchListener'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'hardwareMouseX = clamp01(event.getX() / width)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'return false'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'mvmz_mouse_mode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'mvMouseModeCheck.setText('
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'RunnerCoordinator.saveMvMouseMode'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'InputManager.InputDeviceListener'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'SOURCE_GAMEPAD'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'SOURCE_JOYSTICK'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'setVisibility(hardwarePad && !mouseMode ? GONE : VISIBLE)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'mouseTouchOriginValid'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float dead = baseR * 0.34f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'setMouseCursorNormalized'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'dispatchGenericMotionEvent'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'KEYCODE_BUTTON_L2'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'KEYCODE_BUTTON_R2'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'readRightStickAxis'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'shapeMouseAxis'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameKeyMap.java' 'EngineSettings.keyMap(activity, game.engine)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'GameKeyMap.reset(this, game)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' '"XP".equals(engine)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'keyCode == KeyEvent.KEYCODE_BUTTON_A'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'keyCode == KeyEvent.KEYCODE_BUTTON_START'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'return KeyEvent.KEYCODE_ENTER'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'final float faceGap = 1.45f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float rx = w - s * 0.27f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float ry = h * 0.69f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float shoulderLeftX = rx - d * faceGap'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float shoulderRightX = rx + d * faceGap'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float shoulderBottomY = ry - d * 3.00f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float shoulderTopY = ry - d * 4.20f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float lx = s * 0.25f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'float ly = h - s * 0.27f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'drawDpad'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'insideDpadTouchZone'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'return mouseMode ? insideAnalogZone(x, y) : insideDpadTouchZone(x, y)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'updateDpadDirections'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'dominantRatio = 1.35f'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\VirtualGamepadView.java' 'drawDpadMarker'
if ((Get-Content 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' -Raw) -match 'TouchInput\._events\.wheelY') {
    throw 'A145 wheel path must use standard DOM WheelEvent only'
}
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'rpgmpInputDeviceListener'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'hasRpgmpHardwareGamepad'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'uiVisible && !hasRpgmpHardwareGamepad()'
foreach ($needle in @('KEYCODE_Z','KEYCODE_X','KEYCODE_A','KEYCODE_S','KEYCODE_Q','KEYCODE_W')) {
    Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' $needle
}
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'pathToDocumentIdLower'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'pathToDocumentIdCompat'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'Normalizer.Form.NFKC'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'resolveRequestDocumentId'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'RESOURCE_MISS'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' '404, "Not Found"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'new ByteArrayInputStream(body)'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' '__rpgmp_flicker_compat.js'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'rpgmp-flicker-compat'
if (Test-Path (Join-Path $PSScriptRoot '..\app\src\main\assets\mvmz_flicker_compat.js')) { throw 'A054 flicker compatibility asset must be absent' }
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'IMAGE_WARMUP_'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'imageWarmupPaths'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmpImageWarmupStarted'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'RPGMP IMAGE WARMUP'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'Sprite_Picture.prototype'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'ImageManager.loadBitmap=function'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'detectAggressiveTextureGc()'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'aggressiveTextureGc'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmpTextureGcGuard'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'detectTransitionFrameSkipRisk()'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'transitionFrameSkipRisk'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmpTransitionNoSkip'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'detectWebglPresentationRisk()'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'webglPresentationRisk'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'preserveDrawingBuffer'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'LAYER_TYPE_SOFTWARE'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'Canvas + ?뚰봽?몄썾???⑹꽦 (吏꾨떒)'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmpSmoothFade'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'time-based fade presentation active'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameLog.java' 'new File(root, "_log")'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'GameLog.prepare'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'setWebChromeClient'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'installRenderDiagnostics'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' '[RPGMP-DIAG]'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'detectPixiTextureSlotRisk()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'rewritePixiJs'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'recovered invalid texture slot -1'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmpSlot'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'rewriteManagersJs'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'RPGMP one fade update per presented frame'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'text.setTextSize(ts(16.5f))'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'marqueeGameId'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'postInvalidateOnAnimation()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'touchArmedGameId'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'boolean secondTap = id.equals(touchArmedGameId)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'totalMove > touchSlop'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherView.java' 'selectTouchedGame(upGame, y)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'nodeCompat'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' '__rpgmp_node_compat.js'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'detectNodeCompat'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'new NodeCompatBridge()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'mainModuleFilename()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'readBase64(String path)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'normalizeNodePath'
Require-Text 'app\src\main\assets\mvmz_node_compat.js' "id === 'fs'"
Require-Text 'app\src\main\assets\mvmz_node_compat.js' "id === 'path'"
Require-Text 'app\src\main\assets\mvmz_node_compat.js' "id === 'nw.gui'"
Require-Text 'app\src\main\assets\mvmz_node_compat.js' "id === 'child_process'"
Require-Text 'app\src\main\assets\mvmz_node_compat.js' 'BufferCompat'
Require-Text 'app\src\main\assets\mvmz_node_compat.js' 'rpgmp-android-stub'
Require-Text 'app\src\main\assets\mvmz_node_compat.js' 'bridge.readBase64'
Require-Text 'app\src\main\assets\mvmz_node_compat.js' 'var trailing = raw.length > 1'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'legacy collapsed save path fallback'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'newer legacy save selected'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'old.lastModified > normal.lastModified'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'read save path='
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'write save path='
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'function StorageManager'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'managerPrelude'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'MV local mode disabled; persistent WebStorage active'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'S.isLocalMode=function(){return false;}'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'prepareGameFolderSaveCache()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'game-folder save cache engine='
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'putGameFolderSave'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' '.rmmzsave'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'LZString.compressToBase64'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'MV common-save game-folder bridge active'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'PersistentSaveManager.prepareCentralWebSaveCache('
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'PersistentSaveManager.putCentralWebSave('
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' '!"saves".equalsIgnoreCase(child.name)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'KEY_ACTIVE_GAME_PROCESS'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'GAME_PROCESS_FORCE_KILL_AFTER_MS = 3000L'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'beginGameShutdownGate(activeProcess)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'shutdown gate begin process='
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'findOwnGameProcessPid(processName)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'android.os.Process.killProcess(stuckPid)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'PersistentSaveManager.finishPending(this)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'shutdown gate process gone process='
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'gameShutdownGateRunning'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'suffix = ":mvmz"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'suffix = ":easyrpg"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\LauncherActivity.java' 'suffix = ":mkxp"'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'legacy_giflibrary_wrapper?'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'RPGMP_NATIVE_GIF_DLL_BYPASS'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'GIFLIBRARY PREPASS native mkxp-z bridge'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\gif_native_bridge.rb' 'RPGMP native GifLibrary compatibility bridge'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\gif_native_bridge.rb' 'animated?'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\gif_native_bridge.rb' 'frame_count'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\gif_native_bridge.rb' 'current_frame'
Require-Text 'app\src\main\assets\rgss_compat\cicpoffs\ports\gif_native_bridge.rb' 'goto_and_stop'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'new File(compatCommon, "kgl2_wrap.rb")'
Require-Text 'app\src\main\assets\rgss_compat\common\kgl2_wrap.rb' 'KGL2.klib compatibility for mkxp-z / Android'
Require-Text 'app\src\main\assets\rgss_compat\common\kgl2_wrap.rb' 'class KglLightShader'
Require-Text 'app\src\main\assets\rgss_compat\common\kgl2_wrap.rb' 'class KglShadowShaderW'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\bitmap-binding.cpp' '_kgl_invert'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\bitmap-binding.cpp' '_kgl_compress_alpha'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\bitmap-binding.cpp' '_kgl_subtract_rect'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\bitmap-binding.cpp' '_kgl_shadow_shader_h'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\bitmap-binding.cpp' '_kgl_shadow_shader_v'
Require-Text 'tools\build_selfbuilt_mkxp_arm64.sh' 'binding/bitmap-binding.cpp'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'rpgmp-android-compat'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzCompatibility.java' 'khasultralighting'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'endGame();'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'TAG_RPGMP_KEYMAP'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'remapRpgmpKey'
Require-Text 'app\src\main\AndroidManifest.xml' 'android:process=":mkxp"'
Require-Text 'app\src\main\AndroidManifest.xml' 'android:process=":mvmz"'
Require-Text 'app\src\main\AndroidManifest.xml' 'android:process=":easyrpg"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'explicitExitRequested'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'explicitExitRequested'
Require-Text 'easyrpg_runtime\src\main\java\org\easyrpg\player\player\EasyRpgPlayerActivity.java' 'rpgmpExplicitExitRequested'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'decor.getWindowInsetsController()'
Reject-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MvMzPlayerActivity.java' 'getWindow().getInsetsController()'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'RubyRuntimeHeuristics.inspect'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'RUBY_FALLBACK_STARTUP_TIMEOUT_MS'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'rubySuccessMarker'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\MkxpPlayerActivity.java' 'RPGMP_AUTO_RUBY_FALLBACK'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RubyRuntimeHeuristics.java' 'syntax=kwargs'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' 'readSmallText(context, treeUri, gameIni.documentId)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameScanner.java' 'new String(out.toByteArray(), StandardCharsets.UTF_8)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameLocaleSettings.java' 'Os.setenv("MKXP_GAME_LOCALE"'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\GameLocaleSettings.java' 'Locale.setDefault(locale)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\RunnerCoordinator.java' 'GameLocaleSettings.effective(activity, game)'
Require-Text 'app\src\main\java\com\dj5927\rpgmakerplayer\EngineSettings.java' 'static String locale('
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\util\encoding.h' 'std::string charset = getCharset(str)'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\util\encoding.h' 'iconv_open("UTF-8", charset.c_str())'
Reject-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\src\util\encoding.h' 'CP949'
Require-Text 'tools\build_selfbuilt_mkxp_arm64.sh' 'src/config.cpp'
Require-Text 'tools\build_selfbuilt_mkxp_arm64.sh' 'src/util/encoding.h'
Require-Text 'tools\build_selfbuilt_mkxp_arm64.sh' 'binding/audio-binding.cpp'
Require-Text 'tools\build_selfbuilt_mkxp_arm64.sh' 'patch_mkxpz_android_bridge.py'
Require-Text 'tools\patch_mkxpz_android_bridge.py' 'RPGMP_ANDROID_LAUNCH_BRIDGE_V2'
Require-Text 'tools\patch_mkxpz_android_bridge.py' 'baseConfPath = argv[1]'
Require-Text 'tools\patch_mkxpz_android_bridge.py' 'readConfFile(baseConfPath)'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\audio-binding.cpp' 'rb_define_module("FmodEx")'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\audio-binding.cpp' '"set_loop_points"'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\audio-binding.cpp' '"bgm_play"'
Require-Text 'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z\binding\audio-binding.cpp' '"se_play"'
Require-Text 'app\src\main\assets\rgss_compat\common\win32_wrap.rb' 'module Display'
Require-Text 'app\src\main\assets\rgss_compat\common\win32_wrap.rb' 'module RGSS_FmodEx'
Require-Text 'app\src\main\assets\rgss_compat\common\win32_wrap.rb' 'module Rubyscreen'
Require-Text 'app\src\main\assets\rgss_compat\common\native_ext_compat.rb' 'def Graphics.screenshot'
Require-Text 'app\src\main\assets\rgss_compat\common\native_ext_compat.rb' 'def scroll_up'
Require-Text 'app\src\main\assets\rgss_compat\common\native_ext_compat.rb' 'def to_negative'
Require-Text 'app\src\main\assets\rgss_compat\common\native_ext_compat.rb' 'def add_outline'
Require-Text 'app\src\main\assets\rgss_compat\common\native_ext_compat.rb' 'def set_pattern'
Require-Text 'app\src\main\assets\rgss_compat\common\native_ext_compat.rb' 'def compare_klein_bitmaps'
Require-Text 'app\src\main\assets\rgss_compat\common\cicpoffs_compat.rb' 'KLEIN BITMAP PREPASS native compat'

$compatRoot = Join-Path $root 'app\src\main\assets\rgss_compat'
if (-not (Test-Path (Join-Path $compatRoot 'common\win32_wrap.rb'))) { throw 'win32_wrap asset missing' }
if (-not (Test-Path (Join-Path $compatRoot 'common\mkxp_wrap.rb'))) { throw 'mkxp_wrap asset missing' }
if (-not (Test-Path (Join-Path $compatRoot 'common\ruby_classic_wrap.rb'))) { throw 'ruby_classic_wrap asset missing' }
if (-not (Test-Path (Join-Path $compatRoot 'common\native_ext_compat.rb'))) { throw 'native_ext_compat asset missing' }
if (-not (Test-Path (Join-Path $compatRoot 'common\fix_volume.rb'))) { throw 'fix_volume asset missing' }
if (-not (Test-Path (Join-Path $compatRoot 'cicpoffs\ports\mouse_skip.rb'))) { throw 'mouse_skip asset missing' }
if (-not (Test-Path (Join-Path $compatRoot 'common\cicpoffs_compat.rb'))) { throw 'cicpoffs_compat asset missing' }
$compatFiles = @(Get-ChildItem $compatRoot -Recurse -File)
if ($compatFiles.Count -lt 30) { throw "RGSS compat asset set too small: $($compatFiles.Count)" }

$font = Join-Path $root 'app\src\main\assets\fonts\wqymicrohei.ttf'
if (-not (Test-Path $font)) { throw 'Korean fallback font asset missing' }
if ((Get-Item $font).Length -lt 4000000) { throw 'Korean fallback font asset unexpectedly small' }
foreach ($mk in @(
    'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z-187.mk',
    'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z-193.mk',
    'vendor\mkxp-z-android-mtool-reference\app\jni\mkxp-z.mk'
)) {
    Require-Text $mk 'MKXPZ_CJK_FONT'
}

Require-Text 'vendor\android-mkxp-reference\app\src\main\jni\mkxp\binding-mri\binding-mri.cpp' 'RPGMP_ANDROID_CICPOFFS_PRE_EVAL'
Require-Text 'vendor\android-mkxp-reference\app\src\main\jni\mkxp\binding-mri\binding-mri.cpp' 'compat/common/cicpoffs_compat.rb'

foreach ($probe in @('libprobe-ruby18.so','libprobe-ruby19.so','libprobe-ruby31.so')) {
    $probePath = Join-Path $root ('app\src\main\jniLibs\arm64-v8a\' + $probe)
    if (-not (Test-Path $probePath)) { throw "Ruby probe missing: $probe" }
    if ((Get-Item $probePath).Length -lt 1000000) { throw "Ruby probe unexpectedly small: $probe" }
}

Write-Output 'ANDROID_STORAGE_RUNNER_SMOKE_PASS'
Write-Output ("RGSS_COMPAT_ASSET_COUNT=" + $compatFiles.Count)
