plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dj5927.rpgmakerplayer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.dj5927.rpgmakerplayer'
        minSdk 26
        targetSdk 36
        versionCode 149
        versionName '0.14.9-a149'
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
}

dependencies {
    implementation project(':easyrpg_runtime')
}

